### ISSUE TITLE
garage

### ISSUE THREAD

**Issue by tanguy603** [SuperPommeDeTerre/WoTClanTool#11]
salut je t'envoie le fichier nous avons encore des petits soucis j'espère que ça pourra t'aider

au garage ça se bloque à génération et nous avons rien

**Comment by tanguy603** [comment]
garage.js:233 Uncaught TypeError: Cannot set property 'owners' of undefined(anonymous function) @ garage.js:233i @ jquery-2.2.4.min.js:2fireWith @ jquery-2.2.4.min.js:2z @ jquery-2.2.4.min.js:4(anonymous function) @ jquery-2.2.4.min.js:4

**Comment by SuperPommeDeTerre** [comment]
Salut ! Ça devrait être corrigé...

**Comment by tanguy603** [comment]
Salut je te remercie peux-tu m'envoyer la correction quand tu l'as fait ça serait sympa bonne journée à toi

Cimalando tanguy

Date: Thu, 16 Jun 2016 05:25:19 -0700

**Comment by SuperPommeDeTerre** [comment]
Yep. Tu prends le fichier garage.js ici : https://raw.githubusercontent.com/SuperPommeDeTerre/WoTClanTool/master/js/pages/garage.js
Ensuite, tu le dépose sur ton serveur dans le sous-répertoire js/pages de ton installation, et voilà !

**Comment by tanguy603** [comment]
merci pour ta réactivité mais malheureusement ça ne marche toujours pas

Cimalando tanguy

Date: Thu, 16 Jun 2016 06:32:13 -0700

**Comment by tanguy603** [comment]
merci

Cimalando tanguy

From: tanguy-tanguy@hotmail.fr
To: reply@reply.github.com
Subject: RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)
Date: Thu, 16 Jun 2016 16:21:24 +0200




merci pour ta réactivité mais malheureusement ça ne marche toujours pas

Cimalando tanguy

Date: Thu, 16 Jun 2016 06:32:13 -0700

**Comment by SuperPommeDeTerre** [comment]
Bon, même procédure que précédemment...
J'ai l'impression qu'un char n'est pas trouvé dans le tankopedia... J'ai mis une sécurité !

**Comment by tanguy603** [comment]
je ne sais pas comment le télécharger lol

Cimalando tanguy

Date: Thu, 16 Jun 2016 07:49:31 -0700

**Comment by tanguy603** [comment]
ok j'ai réussi à le télécharger mais maintenant il y a carrément plus rien la page est toute blanche

Cimalando tanguy

Date: Thu, 16 Jun 2016 07:50:13 -0700

**Comment by SuperPommeDeTerre** [comment]
Oups... Un break foireux. Recommence stp.

**Comment by tanguy603** [comment]
désolé ça ne fonctionne pas ou alors j'ai pas bien copier un fichier je ne sais pas
http://tanguy.cimalando.perso.sfr.fr/wct/home

Cimalando tanguy

Date: Thu, 16 Jun 2016 08:52:12 -0700

**Comment by SuperPommeDeTerre** [comment]
Bon, j'ai dû faire quelque chose qu'il ne fallait pas...
Je continuerais à chercher demain. Si tu as des logs (c'est une page sur laquelle j'en avais mis, si tu te rappelle, l'icône en bas à droite), je veux bien que tu les ajoute à cette fiche.
Merci.

**Comment by tanguy603** [comment]
salut voici le fichier logs merci

Cimalando tanguy

Date: Thu, 16 Jun 2016 14:36:47 -0700

**Comment by SuperPommeDeTerre** [comment]
Bon, je viens de faire un test avec les données que tu m'as envoyées, et ça fonctionne bien aussi bien sous Firefox que sous Chrome...  (Bon, les données des chars des membres du clan sont incomplètes, elles ont été tronquées lors du copier/coller)
Est-ce que tu utilise un navigateur particulier ?
Est-ce que tu peux récupérer l'intégralité du dernier appel (dataStoredPlayersTanksResponse) ?

**Comment by tanguy603** [comment]
désolé je ne sais pas faire tout ce que tu me demandes je t'envoie je t'envoie la capture mais sur tous les navigateurs ça fait pareil
et moi quand il y a une mise à jour je écrase tout pour pas perdre nos cartes
Cimalando tanguy

Date: Fri, 17 Jun 2016 00:18:09 -0700

**Comment by SuperPommeDeTerre** [comment]
C'est normal. Ne t'inquiètes pas !
Une solution, ça serait que tu invite mon second compte (The_Masked_Cucumber) dans ton clan, le temps que je debugge ce problème.
Est-ce que ça te paraît faisable ?

**Comment by tanguy603** [comment]
ok pas de blem

Cimalando tanguy

Date: Fri, 17 Jun 2016 00:40:38 -0700

**Comment by tanguy603** [comment]
sur quel compte je dois inviter

Cimalando tanguy

From: tanguy-tanguy@hotmail.fr
To: reply@reply.github.com
Subject: RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)
Date: Fri, 17 Jun 2016 09:48:02 +0200




ok pas de blem

Cimalando tanguy

Date: Fri, 17 Jun 2016 00:40:38 -0700

**Comment by SuperPommeDeTerre** [comment]
J'ai envoyé ma postulation en tant que "The_Masked_Cucumber".

**Comment by SuperPommeDeTerre** [comment]
Merci pour m'avoir accepté. Je suis en train de tester...
Résultat : En local, ça fonctionne, et sur ton install, non...
J'ai essayé de mettre une sécurité supplémentaire, mais c'est pas encore gagné. Je ne comprends pas pourquoi tu as ce comportement...

**Comment by SuperPommeDeTerre** [comment]
Donc, récupération du fichier ici : https://raw.githubusercontent.com/SuperPommeDeTerre/WoTClanTool/master/js/pages/garage.js
Puis dépôt sur ton serveur dans js/pages/.

**Comment by tanguy603** [comment]
Salut je te remercie tout fonctionne correctement tu es le meilleur continue comme ça ton outils est vraiment très bien on s'en sert tous les jours tu peux venir nous voir sur le mumble quand tu veux ça sera avec grand plaisir milles merci de ton travail

Cimalando tanguy

Date: Fri, 17 Jun 2016 02:25:52 -0700

**Comment by SuperPommeDeTerre** [comment]
Merci pour tes encouragements !
En ce moment, ça avance pas trop, car j'ai pas mal de taf, mais il y a des choses dans les tuyaux, comme tu peux le constater !

**Comment by SuperPommeDeTerre** [comment]
Merci pour tes encouragements !
En ce moment, ça avance pas trop, car j'ai pas mal de taf, mais il y a des choses dans les tuyaux, comme tu peux le constater !

**Comment by tanguy603** [comment]
oui super  travail  merci

Cimalando tanguy

Date: Fri, 17 Jun 2016 03:51:02 -0700

**Comment by tanguy603** [comment]
Salut Je t'écris pour te demander si tu peux intégrer le lien que je te donne car il est carrément plus rapide chez nous la map et vraiment trop longue et on ne peut pas ping s si tu ne peux pas est-ce que tu peux faire un lien dynamique dans le commentaire des événements cordialement
http://wottactic.com/

Cimalando tanguy

Date: Fri, 17 Jun 2016 02:24:45 -0700

**Comment by tanguy603** [comment]
Salut j'ai changé le serveur d'hébergement et j'ai un gros soucis ça fonctionne et dès que j'arrive à l'identifiant ça se plante peux-tu me donner une solution merci
http://cf1.alwaysdata.net/

Cimalando tanguy

From: tanguy-tanguy@hotmail.fr
To: reply@reply.github.com
Subject: RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)
Date: Fri, 17 Jun 2016 14:51:22 +0200




oui super  travail  merci

Cimalando tanguy

Date: Fri, 17 Jun 2016 03:51:02 -0700

**Comment by SuperPommeDeTerre** [comment]
On dirait que le .htaccess est incorrect.
Essaye de le modifier en mettant la directive "RewriteBase" à "RewriteBase /".

**Comment by tanguy603** [comment]
voici ce qui est marqué dans le fichierRewriteBase /wct/

Cimalando tanguy

Date: Wed, 29 Jun 2016 00:49:32 -0700

**Comment by SuperPommeDeTerre** [comment]
C'est ça ! Mets juste "/" au lieu de "/wct".

**Comment by tanguy603** [comment]
ok merci tu es trop fort il faudra quand même que tu viennes sur le même bol qu'on puisse parler ensemble encore merci merci

Cimalando tanguy

Date: Wed, 29 Jun 2016 02:30:40 -0700

**Comment by SuperPommeDeTerre** [comment]
J'aimerais bien, mais je ne trouve pas le mdp du Mumble... :-(

**Comment by tanguy603** [comment]
http://www.clubic.com/telecharger-fiche43179-mumble.html

mumble  adresse:     CompagnieFantome.upmania.eu port :51153 Mot de passe : toto

Cimalando tanguy

Date: Wed, 29 Jun 2016 02:42:44 -0700

**Comment by SuperPommeDeTerre** [comment]
C'est noté, merci ! Je passerais ce soir !
Sinon, je supprime ton commentaire pour ne pas laisser l'info sur github...

**Comment by tanguy603** [comment]
Salut Je t'écris pour te dire que nous avons quelques difficultés avec la maptactic notamment avec le système de flèche mais Strateur n'arrive pas à bien utilisez les flèches pour indiquer les zones est-ce que tu pourrais trouver une solution cordialement


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : mercredi 29 juin 2016 11:42:44
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


J'aimerais bien, mais je ne trouve pas le mdp du Mumble... :-(

-

**Comment by tanguy603** [comment]
Salut Je t'écris pour te dire que nous avons quelques difficultés avec la maptactic notamment avec le système de flèche mais Strateur n'arrive pas à bien utilisez les flèches pour indiquer les zones est-ce que tu pourrais trouver une solution cordialement


Cimalando tanguy
________________________________
De : tanguy c <tanguy-tanguy@hotmail.fr>
Envoyé : mercredi 29 juin 2016 11:45:53
À : SuperPommeDeTerreWoTClanTool
Objet : RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)

http://www.clubic.com/telecharger-fiche43179-mumble.html


mumble  adresse:     CompagnieFantome.upmania.eu
 port :51153
Mot de passe : toto

Cimalando tanguy

________________________________
Date: Wed, 29 Jun 2016 02:42:44 -0700

**Comment by SuperPommeDeTerre** [comment]
Bonjour,

Est-ce que tu pourrais m'en dire plus sur les difficultés rencontrées ? Ca me permettra de déterminer une solution possible. Merci.

**Comment by tanguy603** [comment]
Salut nous avons un problème avec les traits car il faut sortir de la page pour pouvoir arrêter les traits et il n'y a pas de flèche de direction ça serait mieux

si non passe sur notre mumble je t'expliquerai plus en détail merci pour tout


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 25 juillet 2016 08:46:24
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Bonjour,

Est-ce que tu pourrais m'en dire plus sur les difficultés rencontrées ? Ca me permettra de déterminer une solution possible. Merci.

-

**Comment by tanguy603** [comment]
Salut Je t'écris pour te dire qu'on a des difficultés pour les trait sur la map tactique si tu fais des prêts et que tu enregistres tu aurais ouvre la carte certains traits ont disparu

et aussi quand tu te fais un trait sur la carte pour arrêter il faut sortir de l'écran pour arrêter un peu galère

Cimalando Tanguy

________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 25 juillet 2016 08:46:24
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Bonjour,

Est-ce que tu pourrais m'en dire plus sur les difficultés rencontrées ? Ca me permettra de déterminer une solution possible. Merci.

-

**Comment by tanguy603** [comment]
Salut j'ai créé un deuxième clan  je voudrais savoir comment je peux l'intégrer dans notre wot  ct  merci

Cimalando tanguy
________________________________
De : tanguy c <tanguy-tanguy@hotmail.fr>
Envoyé : mardi 2 août 2016 20:12:36
À : SuperPommeDeTerre/WoTClanTool
Objet : RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Salut Je t'écris pour te dire qu'on a des difficultés pour les trait sur la map tactique si tu fais des prêts et que tu enregistres tu aurais ouvre la carte certains traits ont disparu

et aussi quand tu te fais un trait sur la carte pour arrêter il faut sortir de l'écran pour arrêter un peu galère

Cimalando Tanguy

________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 25 juillet 2016 08:46:24
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Bonjour,

Est-ce que tu pourrais m'en dire plus sur les difficultés rencontrées ? Ca me permettra de déterminer une solution possible. Merci.

-

**Comment by tanguy603** [comment]
Bonjour je voudrais savoir quel est le fichier à sauvegarder pour les maps tactic car nous avons un deuxième clan et il faudrait que je rentre à l' pour autoriser et deux en même temps cordialement


Cimalando tanguy
________________________________
De : tanguy c <tanguy-tanguy@hotmail.fr>
Envoyé : lundi 22 août 2016 11:45:13
À : SuperPommeDeTerre/WoTClanTool
Objet : RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)



Salut j'ai créé un deuxième clan  je voudrais savoir comment je peux l'intégrer dans notre wot  ct  merci

Cimalando tanguy
________________________________
De : tanguy c <tanguy-tanguy@hotmail.fr>
Envoyé : mardi 2 août 2016 20:12:36
À : SuperPommeDeTerre/WoTClanTool
Objet : RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Salut Je t'écris pour te dire qu'on a des difficultés pour les trait sur la map tactique si tu fais des prêts et que tu enregistres tu aurais ouvre la carte certains traits ont disparu

et aussi quand tu te fais un trait sur la carte pour arrêter il faut sortir de l'écran pour arrêter un peu galère

Cimalando Tanguy

________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 25 juillet 2016 08:46:24
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Bonjour,

Est-ce que tu pourrais m'en dire plus sur les difficultés rencontrées ? Ca me permettra de déterminer une solution possible. Merci.

-

**Comment by tanguy603** [comment]
Bonjour

nous avons un gros problème avec les map tactic  de wot ct  ça ne fonctionne plus

cordialement

toto603 (CF1)

**Comment by SuperPommeDeTerre** [comment]
Salut,

Désolé de ne pas avoir répondu à toutes tes questions, je suis légèrement débordé en ce moment, ce qui fait que j'ai laissé en pause le projet.
Concernant tes problématiques :

- Effectivement, l'enregistrement pose problème, j'ai reproduit le problème. Je vais tenter de le corriger.
- Il n'y a pas moyen actuellement de faire des clans "amis". C'est une fonctionnalité à implémenter mais c'est un peu complexe...
- Pour les strats, elles sont enregistrées dans le dossier "data/EU/[ID CLAN]/strats/". Par contre, tu as un fichier "list.json" dans ce répertoire que tu dois modifier pour en avoir la visibilité.
- Pour les flèches, tu peux aller dans les propriétés de la ligne (si tu mets ta souris dessus, tu as des carrés gris qui apparaissent au niveau des points, et si tu mets ta souris dessus, tu as un petit menu qui apparaît. Tu cliques alors sur la roue crantée pour modifier les propriétés de la ligne, dont les flèches de début et fin)

**Comment by tanguy603** [comment]
merci pour tes réponses j'essaie de m'installer mais c'est très compliqué ça ne veut pas fonctionner[cid:c6b12976-62d7-438e-aaa0-a022a4531ce2]


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : mercredi 12 octobre 2016 09:44:49
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Salut,

Désolé de ne pas avoir répondu à toutes tes questions, je suis légèrement débordé en ce moment, ce qui fait que j'ai laissé en pause le projet.
Concernant tes problématiques :

  *   Effectivement, l'enregistrement pose problème, j'ai reproduit le problème. Je vais tenter de le corriger.
  *   Il n'y a pas moyen actuellement de faire des clans "amis". C'est une fonctionnalité à implémenter mais c'est un peu complexe...
  *   Pour les strats, elles sont enregistrées dans le dossier "data/EU/[ID CLAN]/strats/". Par contre, tu as un fichier "list.json" dans ce répertoire que tu dois modifier pour en avoir la visibilité.
  *   Pour les flèches, tu peux aller dans les propriétés de la ligne (si tu mets ta souris dessus, tu as des carrés gris qui apparaissent au niveau des points, et si tu mets ta souris dessus, tu as un petit menu qui apparaît. Tu cliques alors sur la roue crantée pour modifier les propriétés de la ligne, dont les flèches de début et fin)

-

**Comment by tanguy603** [comment]
Salut nous avons un gros problème nous pouvons plus utiliser maptactic depuis une semaine je t'envoie la photo ça reste bloqué sur générations


Cimalando tanguy
________________________________
De : tanguy c <tanguy-tanguy@hotmail.fr>
Envoyé : mercredi 12 octobre 2016 09:51:33
À : SuperPommeDeTerre/WoTClanTool
Objet : RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)


merci pour tes réponses j'essaie de m'installer mais c'est très compliqué ça ne veut pas fonctionner[cid:c6b12976-62d7-438e-aaa0-a022a4531ce2]


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : mercredi 12 octobre 2016 09:44:49
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Salut,

Désolé de ne pas avoir répondu à toutes tes questions, je suis légèrement débordé en ce moment, ce qui fait que j'ai laissé en pause le projet.
Concernant tes problématiques :

  *   Effectivement, l'enregistrement pose problème, j'ai reproduit le problème. Je vais tenter de le corriger.
  *   Il n'y a pas moyen actuellement de faire des clans "amis". C'est une fonctionnalité à implémenter mais c'est un peu complexe...
  *   Pour les strats, elles sont enregistrées dans le dossier "data/EU/[ID CLAN]/strats/". Par contre, tu as un fichier "list.json" dans ce répertoire que tu dois modifier pour en avoir la visibilité.
  *   Pour les flèches, tu peux aller dans les propriétés de la ligne (si tu mets ta souris dessus, tu as des carrés gris qui apparaissent au niveau des points, et si tu mets ta souris dessus, tu as un petit menu qui apparaît. Tu cliques alors sur la roue crantée pour modifier les propriétés de la ligne, dont les flèches de début et fin)

-

**Comment by SuperPommeDeTerre** [comment]
Salut, j'ai corrigé le pb des lignes qui disparaissaient lors de l'import. il faut récupérer le fichier js/pages/strats.js

**Comment by tanguy603** [comment]
je suis désolé mais ça ne fonctionne pas toute la partie stratégie reste sur la page génération

________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : jeudi 13 octobre 2016 11:07:53
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Salut, j'ai corrigé le pb des lignes qui disparaissaient lors de l'import. il faut récupérer le fichier js/pages/strats.js

-

**Comment by SuperPommeDeTerre** [comment]
J'ai fais une autre correction. Le problème provient du fait que le créateur de la stratégie ne fais plus partie du clan.

**Comment by tanguy603** [comment]
ok merci super


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : jeudi 13 octobre 2016 12:41:53
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


J'ai fais une autre correction. Le problème provient du fait que le créateur de la stratégie ne fais plus partie du clan.

-

**Comment by tanguy603** [comment]
salut

je suis désolé de t'embêter encore avant la modification nom deux clan (cf1-cf2) pouvait se connecter maintenant il y a plus que les CF1 as-tu une solution pour moi

merci

Cimalando tanguy
________________________________
De : tanguy c <tanguy-tanguy@hotmail.fr>
Envoyé : jeudi 13 octobre 2016 15:05:39
À : SuperPommeDeTerre/WoTClanTool
Objet : RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)


ok merci super


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : jeudi 13 octobre 2016 12:41:53
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


J'ai fais une autre correction. Le problème provient du fait que le créateur de la stratégie ne fais plus partie du clan.

-

**Comment by SuperPommeDeTerre** [comment]
Il faudrait vérifier que ton deuxième clan est bien dans la liste des clans autorisés (page d'administration).
Je peux le vérifier si tu me fournis ton fichier "config/config.json".

**Comment by tanguy603** [comment]
salut merci de ta réponse voici la ligne d'écriture cordialement


{"WG":{"clusters":["EU"]},"app":{"theme":"default","admins":{"EU":["506533625"]},"showads":true},"clans":{"restric_to":{"EU":["500068744"]}},"player":{"max_battle_time":"30"}}

Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 17 octobre 2016 09:24:19
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Il faudrait vérifier que ton deuxième clan est bien dans la liste des clans autorisés (page d'administration).
Je peux le vérifier si tu me fournis ton fichier "config/config.json".

-

**Comment by SuperPommeDeTerre** [comment]
Bon, c'est bien ça. Il faudrait que tu ais ceci :
{"WG":{"clusters":["EU"]},"app":{"theme":"default","admins":{"EU":["506533625"]},"showads":true},"clans":{"restric_to":{"EU":["500068744","500135503"]}},"player":{"max_battle_time":"30"}}

**Comment by tanguy603** [comment]
Non autorisé !

Vous n'êtes pas autorisé à accéder à ce site.

Seul les membres des clans autorisés peuvent se connecter à ce site.


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 17 octobre 2016 09:31:25
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Bon, c'est bien ça. Il faudrait que tu ais ceci :
{"WG":{"clusters":["EU"]},"app":{"theme":"default","admins":{"EU":["506533625"]},"showads":true},"clans":{"restric_to":{"EU":["500068744","500135503"]}},"player":{"max_battle_time":"30"}}

-

**Comment by tanguy603** [comment]
Cimalando tanguy
________________________________
De : tanguy c <tanguy-tanguy@hotmail.fr>
Envoyé : lundi 17 octobre 2016 09:41:01
À : SuperPommeDeTerre/WoTClanTool
Objet : RE: [SuperPommeDeTerre/WoTClanTool] garage (#11)



Non autorisé !

Vous n'êtes pas autorisé à accéder à ce site.

Seul les membres des clans autorisés peuvent se connecter à ce site.


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 17 octobre 2016 09:31:25
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Bon, c'est bien ça. Il faudrait que tu ais ceci :
{"WG":{"clusters":["EU"]},"app":{"theme":"default","admins":{"EU":["506533625"]},"showads":true},"clans":{"restric_to":{"EU":["500068744","500135503"]}},"player":{"max_battle_time":"30"}}

-

**Comment by SuperPommeDeTerre** [comment]
En se déconnectant/reconnectant, ça ne marche pas mieux ?

Ton deuxième clan c'est bien celui-là : [https://eu.wargaming.net/clans/wot/500135503/](url)

**Comment by tanguy603** [comment]
non ca ne marche pas et oui pour le clan cf2


Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 17 octobre 2016 09:51:21
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


En se déconnectant/reconnectant, ça ne marche pas mieux ?

Ton deuxième clan c'est bien celui-là : https://eu.wargaming.net/clans/wot/500135503/<url>

-

**Comment by SuperPommeDeTerre** [comment]
Là, je sèche un peu. Une hypothèse serait que la personne essayant de se connecter est connecté à WG avec un autre compte ne faisant pas partie des clans autorisés (CF1 et CF2).
En effet, je viens d'essayer sur mon instance, et ça marche bien.
Il peut le vérifier en allant ici : [https://eu.wargaming.net/personal/sessions/#applications](url)
Sinon, tu peux enlever les restrictions de clan temporairement en mettant ceci dans ton fichier de configuration :{"WG":{"clusters":["EU"]},"app":{"theme":"default","admins":{"EU":["506533625"]},"showads":true},"clans":{"restric_to":{"EU":[]}},"player":{"max_battle_time":"30"}}

**Comment by tanguy603** [comment]
ok merci super



Cimalando tanguy
________________________________
De : SuperPommeDeTerre <notifications@github.com>
Envoyé : lundi 17 octobre 2016 10:22:10
À : SuperPommeDeTerre/WoTClanTool
Cc : tanguy603; Author
Objet : Re: [SuperPommeDeTerre/WoTClanTool] garage (#11)


Là, je sèche un peu. Une hypothèse serait que la personne essayant de se connecter est connecté à WG avec un autre compte ne faisant pas partie des clans autorisés (CF1 et CF2).
En effet, je viens d'essayer sur mon instance, et ça marche bien.
Il peut le vérifier en allant ici : https://eu.wargaming.net/personal/sessions/#applications<url>
Sinon, tu peux enlever les restrictions de clan temporairement en mettant ceci dans ton fichier de configuration :{"WG":{"clusters":["EU"]},"app":{"theme":"default","admins":{"EU":["506533625"]},"showads":true},"clans":{"restric_to":{"EU":[]}},"player":{"max_battle_time":"30"}}

-
