### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Defskidrow** [SuperPommeDeTerre/WoTClanTool#12]
Hello, I get at the instalaltion always "Internal Server Error" said. How can I avoid that?

**Comment by SuperPommeDeTerre** [comment]
Hi, I haven't touched this part for a while, so I can't give you any clue about it...
But can you give me some informations about yout hosting (phpinfo) ? I'll try to debug this.
Meanwhile, you can use my instance located at [http://wot.pixbuf.net/wct/](http://wot.pixbuf.net/wct/)

**Comment by SuperPommeDeTerre** [comment]
Yeah, the .htaccess file is mandatory (my code is a litlle messy...).
In your case, it'll have to look like this :
```
DirectoryIndex index.php
#Options -Multiviews
<IfModule mod_rewrite.c>
	RewriteEngine on
	RewriteBase /
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-l
	RewriteRule ^strats/(.+)/(.+)$					strats.php?action=$1&view=$2				[QSA,PT,L]
	RewriteRule ^strats/(.+)$						strats.php?action=$1						[QSA,PT,L]
	RewriteRule ^encyclopedia/(.+)$					encyclopedia.php#$1							[QSA,PT,L]
	RewriteRule ^locales/resources/(.+)/(.+).json$	locales/resources.php?a=get&lng=$1&ns=$2	[QSA,PT,L]
	RewriteRule ^([a-zA-Z0-9]+)$					$1.php										[QSA,PT,L]
</IfModule>
```
