### ISSUE TITLE
cf1 log

### ISSUE THREAD

**Issue by tanguy603** [SuperPommeDeTerre/WoTClanTool#9]
[log17.03cf1.txt](https://github.com/SuperPommeDeTerre/WoTClanTool/files/177488/log17.03cf1.txt)

**Comment by SuperPommeDeTerre** [comment]
Parfait !

**Comment by SuperPommeDeTerre** [comment]
J'ai identifié et corrigé le problème. Tu peux récupérer la dernière version et mettre à jour !

**Comment by tanguy603** [comment]
super merci je te donne notre mumble si un jour tu veux venir nous voir ça sera avec plaisir
Lien mumble : CompagnieFantome.upmania.eu port :51153 Mot de passe : toto 
Cimalando tanguy(toto603)

Date: Thu, 17 Mar 2016 03:25:14 -0700

**Comment by SuperPommeDeTerre** [comment]
Ça sera avec plaisir ! (et je pense même que cette échéance risque d'être proche ;))

**Comment by tanguy603** [comment]
super pour le travail tout est revenuje suis le commandant du clan Toto603je suis là tous les soirs sauf le lundi et le jeudi ça sera avec plaisir
Cimalando tanguy

Date: Thu, 17 Mar 2016 04:15:18 -0700
